var hierarchy =
[
    [ "marvin::dsp::filters::Biquad< SampleType, NumStages >", "classmarvin_1_1dsp_1_1filters_1_1Biquad.html", null ],
    [ "marvin::dsp::filters::BiquadCoefficients< SampleType >", "structmarvin_1_1dsp_1_1filters_1_1BiquadCoefficients.html", null ],
    [ "marvin::containers::BufferView< SampleType >", "structmarvin_1_1containers_1_1BufferView.html", null ],
    [ "marvin::containers::StrideView< T, Stride >::const_iterator", "classmarvin_1_1containers_1_1StrideView_1_1const__iterator.html", null ],
    [ "marvin::dsp::DelayLine< SampleType, InterpolationType >", "classmarvin_1_1dsp_1_1DelayLine.html", null ],
    [ "marvin::dsp::spectral::FFT< SampleType >", "classmarvin_1_1dsp_1_1spectral_1_1FFT.html", null ],
    [ "marvin::containers::fifos::FIFO< QueueType, T >", "classmarvin_1_1containers_1_1fifos_1_1FIFO.html", null ],
    [ "marvin::containers::FixedCircularBuffer< T, N >", "classmarvin_1_1containers_1_1FixedCircularBuffer.html", null ],
    [ "marvin::dsp::spectral::getValueType< T >", "structmarvin_1_1dsp_1_1spectral_1_1getValueType.html", null ],
    [ "marvin::dsp::spectral::getValueType< T >", "structmarvin_1_1dsp_1_1spectral_1_1getValueType_3_01T_01_4.html", null ],
    [ "marvin::math::Hadamard< SampleType, size >", "classmarvin_1_1math_1_1Hadamard.html", null ],
    [ "marvin::math::Householder< SampleType, size >", "classmarvin_1_1math_1_1Householder.html", null ],
    [ "marvin::containers::StrideView< T, Stride >::iterator", "classmarvin_1_1containers_1_1StrideView_1_1iterator.html", null ],
    [ "marvin::dsp::filters::LatticeAPF< SampleType >", "classmarvin_1_1dsp_1_1filters_1_1LatticeAPF.html", null ],
    [ "marvin::math::LeakyIntegrator< SampleType >", "classmarvin_1_1math_1_1LeakyIntegrator.html", null ],
    [ "marvin::dsp::filters::LPF< SampleType >", "classmarvin_1_1dsp_1_1filters_1_1LPF.html", null ],
    [ "marvin::dsp::oscillators::MultiOscillator< SampleType, Bandlimit >", "classmarvin_1_1dsp_1_1oscillators_1_1MultiOscillator.html", null ],
    [ "marvin::dsp::oscillators::OscillatorBase< SampleType >", "classmarvin_1_1dsp_1_1oscillators_1_1OscillatorBase.html", [
      [ "marvin::dsp::oscillators::PulseOscillator< SampleType, Bandlimiting::Off >", "classmarvin_1_1dsp_1_1oscillators_1_1PulseOscillator.html", null ],
      [ "marvin::dsp::oscillators::SawOscillator< SampleType, Bandlimiting::Off >", "classmarvin_1_1dsp_1_1oscillators_1_1SawOscillator.html", null ],
      [ "marvin::dsp::oscillators::SquareOscillator< SampleType, Bandlimiting::Off >", "classmarvin_1_1dsp_1_1oscillators_1_1SquareOscillator.html", null ],
      [ "marvin::dsp::oscillators::TriOscillator< SampleType, Bandlimiting::Off >", "classmarvin_1_1dsp_1_1oscillators_1_1TriOscillator.html", null ],
      [ "marvin::dsp::oscillators::NoiseOscillator< SampleType >", "classmarvin_1_1dsp_1_1oscillators_1_1NoiseOscillator.html", null ],
      [ "marvin::dsp::oscillators::PulseOscillator< SampleType, Blep >", "classmarvin_1_1dsp_1_1oscillators_1_1PulseOscillator.html", null ],
      [ "marvin::dsp::oscillators::SawOscillator< SampleType, Blep >", "classmarvin_1_1dsp_1_1oscillators_1_1SawOscillator.html", null ],
      [ "marvin::dsp::oscillators::SineOscillator< SampleType >", "classmarvin_1_1dsp_1_1oscillators_1_1SineOscillator.html", null ],
      [ "marvin::dsp::oscillators::SquareOscillator< SampleType, Blep >", "classmarvin_1_1dsp_1_1oscillators_1_1SquareOscillator.html", null ],
      [ "marvin::dsp::oscillators::TriOscillator< SampleType, Blamp >", "classmarvin_1_1dsp_1_1oscillators_1_1TriOscillator.html", null ]
    ] ],
    [ "marvin::math::windows::PrecomputedWindow< SampleType, NumPoints >", "classmarvin_1_1math_1_1windows_1_1PrecomputedWindow.html", null ],
    [ "marvin::library::PropagateConst< T >", "classmarvin_1_1library_1_1PropagateConst.html", null ],
    [ "marvin::utils::RandomGenerator< Engine >", "classmarvin_1_1utils_1_1RandomGenerator.html", null ],
    [ "marvin::utils::Range< T >", "structmarvin_1_1utils_1_1Range.html", null ],
    [ "marvin::math::Reciprocal< T >", "classmarvin_1_1math_1_1Reciprocal.html", null ],
    [ "marvin::math::ReciprocalRange< T >", "structmarvin_1_1math_1_1ReciprocalRange.html", null ],
    [ "marvin::dsp::filters::SmoothedBiquadCoefficients< SampleType, InterpolationType, NumStages >", "classmarvin_1_1dsp_1_1filters_1_1SmoothedBiquadCoefficients.html", null ],
    [ "marvin::utils::SmoothedValue< SampleType, Type >", "classmarvin_1_1utils_1_1SmoothedValue.html", null ],
    [ "marvin::containers::StrideView< T, Stride >", "classmarvin_1_1containers_1_1StrideView.html", null ],
    [ "marvin::dsp::filters::SVF< SampleType >", "classmarvin_1_1dsp_1_1filters_1_1SVF.html", null ],
    [ "marvin::dsp::filters::SVFResult< SampleType >", "structmarvin_1_1dsp_1_1filters_1_1SVFResult.html", null ],
    [ "marvin::containers::SwapBuffer< T >", "classmarvin_1_1containers_1_1SwapBuffer.html", null ],
    [ "marvin::math::interpolators::WindowedSincInterpolator< SampleType, N, WindowType >", "classmarvin_1_1math_1_1interpolators_1_1WindowedSincInterpolator.html", null ]
];