name: Doxygen Github Pages Deploy Action
on: 
  push: 
    branches: 
      - main

jobs: 
  build-project: 
    name: Build Documentation
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v4.1.2         
      - name: Install doxygen
        uses: ssciwr/doxygen-install@v1 
      - name: Configure
        uses: threeal/cmake-action@main
        with:
          run-build: false
      - name: Doxygen
        uses: mattnotmitt/doxygen-action@v1.1.0 
        with: 
          doxyfile-path: ./build/docs/Doxyfile.marvin_docs
          working-directory: "./docs/doxygen"
