name: Tests
on: 
  push: 
    branches: 
      - main

jobs: 
  build-project: 
    name: Tests
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v4.1.2         
      - name: Build
        uses: threeal/cmake-action@main
        with:
          build-args: "--target marvin-tests"
      - name: Run tests
        run: ./build/marvin-tests

